# Dynamic OS/Architecture Logic
locals {
  # Maps AWS architecture to the .NET Runtime Identifier (RID)
  dotnet_rid = var.lambda_architecture == "arm64" ? "linux-arm64" : "linux-x64"

  # Centralized path for the Lambda ZIP
  lambda_zip_path = "${path.module}/../../../src/ImageProcessor.Lambda/bin/Release/net10.0/${local.dotnet_rid}/publish/ImageProcessor.Lambda.UploadImage.zip"

  # Deterministic hash based on source files (avoids non-deterministic ZIP hashes)
  source_hash = base64sha256(join("", [
    for f in fileset("${path.module}/../../../src/ImageProcessor.Lambda", "**/*.{cs,csproj}") :
    filesha1("${path.module}/../../../src/ImageProcessor.Lambda.UploadImage/${f}")
  ]))
}

# CloudWatch Log Group for Lambda
resource "aws_cloudwatch_log_group" "lambda_log_group" {
  name              = "/aws/lambda/ImageProcessorLambdaUploadImage"
  retention_in_days = 7
}

# IAM Role - Trust Policy
# Allows the AWS Lambda service to assume this identity
resource "aws_iam_role" "lambda_execution_role" {
  name = "image-processor-lambda-role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Action    = "sts:AssumeRole"
        Effect    = "Allow"
        Principal = {
          Service = "lambda.amazonaws.com"
        }
      }
    ]
  })
}

# IAM Policy - Least Privilege
# Defines exact permissions for the Lambda function
resource "aws_iam_role_policy" "lambda_permissions" {
  name = "image-processor-lambda-permissions"
  role = aws_iam_role.lambda_execution_role.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        # Permissions to write to the explicit log group
        Effect = "Allow"
        Action = [
          "logs:CreateLogStream",
          "logs:PutLogEvents"
        ]
        Resource = "${aws_cloudwatch_log_group.lambda_log_group.arn}:*"
      },
      {
        Effect = "Allow"
        Action = [
          "s3:PutObject"
        ]
        Resource = "${var.bucket_arn}/*"
      },
      {
        Effect = "Allow"
        Action = [
          "dynamodb:PutItem"
        ]
        Resource = var.dynamodb_table_arn
      }
    ]
  })
}

# Build & Package - Native terraform_data
# Compiles the .NET project with Native AOT and zips it automatically
resource "terraform_data" "lambda_build" {
  triggers_replace = {
    # Rebuilds whenever any .cs or .csproj file changes
    source_hash = sha1(join("", [
      for f in fileset("${path.module}/../../../src/ImageProcessor.Lambda.UploadImage", "**/*.cs") :
      filesha1("${path.module}/../../../src/ImageProcessor.Lambda.UploadImage/${f}")
    ]))
    csproj_hash = filesha1("${path.module}/../../../src/ImageProcessor.Lambda.UploadImage/ImageProcessor.Lambda.UploadImage.csproj")
  }

  provisioner "local-exec" {
    command     = "dotnet lambda package --configuration Release --framework net10.0 --function-architecture ${var.lambda_architecture} --output-package bin/Release/net10.0/${local.dotnet_rid}/publish/ImageProcessor.Lambda.UploadImage.zip"
    working_dir = "${path.module}/../../../src/ImageProcessor.Lambda.UploadImage"
  }
}

# AWS Lambda Function
resource "aws_lambda_function" "image_processor_lambda_upload_image" {
  function_name = "ImageProcessorLambdaUploadImage"
  role          = aws_iam_role.lambda_execution_role.arn
  handler       = "bootstrap"
  runtime       = "provided.al2023"
  architectures = [var.lambda_architecture]

  # Points directly to the zip generated by terraform_data
  filename         = local.lambda_zip_path
  source_code_hash = local.source_hash

  # Environment variables read by the C# application
  environment {
    variables = {
      BUCKET_NAME = var.bucket_name
      TABLE_NAME  = var.dynamodb_table_name
    }
  }

  depends_on = [
    terraform_data.lambda_build,
    aws_cloudwatch_log_group.lambda_log_group
  ]
}